version: '3'
services:
    mirakurun:
        build:
            context: mirakurun
        container_name: mirakurun
        #cap_add:
        #    - SYS_NICE
        #    - SYS_ADMIN
        privileged: true
        ports:
            - "40772:40772"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mirakurun/conf:/usr/local/etc/mirakurun
            - ./mirakurun/db:/usr/local/var/db/mirakurun
        environment:
            TZ: "Asia/Tokyo"
        devices:
            - /dev/dvb:/dev/dvb
            #- /dev/bus/usb/00x/00x # card reader
        #restart: always

    mysql:
        image: mariadb:latest
        container_name: mysql
        volumes:
            - mysql-db:/var/lib/mysql
        environment:
            MYSQL_USER: epgstation
            MYSQL_PASSWORD: epgstation
            MYSQL_ROOT_PASSWORD: epgstation
            MYSQL_DATABASE: epgstation
            TZ: "Asia/Tokyo"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --performance-schema=false --expire_logs_days=1
        #restart: always

    epgstation:
        build:
            context: epgstation
            args:
                - CPUCORE=2
        container_name: epgstation
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./epgstation/config:/usr/local/EPGStation/config
            - ./epgstation/data:/usr/local/EPGStation/data
            - ./epgstation/thumbnail:/usr/local/EPGStation/thumbnail
            - ./epgstation/logs:/usr/local/EPGStation/logs
            - ./recorded:/usr/local/EPGStation/recorded
        environment:
            TZ: "Asia/Tokyo"
        devices:
            - /dev/dri:/dev/dri
        links:
            - mirakurun:mirakurun
            - mysql:mysql
        ports:
            - "8888:8888"
            - "8889:8889"
        #user: "1000:1000"
        #restart: always

volumes:
    mysql-db:
        driver: local

